Added regions to ModelResults object
tetonsim/pywim pull request #74
Opened 2020-11-06 22:17 UTC by jlselden

Closes #71 

Adds `model_regions` attribute to `pywim.fea.result.ModelResults` consisting of a `WimList` of `ModelRegion` objects. The `ModelRegion` object contains a list of meshes in the `region` attribute. It should be noted that these meshes can be disconnected, so a region could consist of several disjoint componenets.

2020-11-06 22:24 UTC, jlselden commented
Changed to draft for the following reason.

A related issue for this topic is control over the size of the regions that we generate. This should be a parameter in `pywim.smartslice.job`, but I'm not sure if that change belongs in this PR or not.

2020-11-06 22:49 UTC, jlselden commented
@bradymadams I can envision other ways of determining regions in the model (number of elements, for example), so I thought I should set things up to generalize. Let me know if this is going overboard.

2020-11-06 23:04 UTC, bradymadams requested changes
I agree with the overall structure. Just some minor change requests.

In response to your question about it going overboard - I think you could remove `PercentileRegion` and just put `percentile` into `ModelRegion` for now. In fact, the way you have it won't deserialize correctly from JSON into the Job object. To use inheritance with our JSON serialization/deserialization logic you have to set `type` attributes, and a class level `JSONTYPENAME` attribute (you can look in pywim.fea.model for examples if you're interested). It's not crazy difficult, but I think it might just be easier to use a single class for now.

2020-11-06 23:07 UTC, jlselden commented on pywim/smartslice/job.py
> +    def __init__(self, name, percentile : float = 20.):
Got it. I noticed that in the style guide, but since we had been consistently using the space, I just stayed with it. I'll try to make the change going forward.

2020-11-06 23:11 UTC, jlselden commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
I was thinking that we could use the region name to differentiate the regions, e.g., 'high_strain' indicates what we are identifying and leaves it to the UI to interpret the region as a "problem region". That said, I'm not against calling this list `problem_regions`.

2020-11-06 23:19 UTC, bradymadams commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
In that case, I agree with you. But taking that even further - should we even use the qualifiers "low" and "high". We could just say "strain" and attach a condition to it. That could allow the tool to be used to identify low strain regions, for example, so they could locate regions where they could remove material.

That would open up the question of how we'd name the regions in the result, though, if we received two region requests for the same result, like a low strain, and high strain.

Maybe I'm taking it too far now...

2020-11-06 23:26 UTC, jlselden commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
Yeah, I was trying to be sophisticated in the simplest possible way, putting all the responsibility on the name, which probably isn't very robust. I think for the time being, your initial suggestion makes more sense, i.e., problem_regions. I would need to build more flexibility into the way the regions are generated in order to accommodate different conditions. Currently, it always chooses for high strain and/or low FOS.

2020-11-06 23:26 UTC, jlselden commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
However, if you think it's worth it, I'm down.

2020-11-06 23:28 UTC, bradymadams commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
I'm fine with either way, TBH, but if we're going for the flexible approach we should probably make it truly flexible. If we just call it `problem_regions` we could keep it simple and then use `model_regions` in the future to make it more flexible, if it becomes necessary.

2020-11-06 23:29 UTC, bradymadams commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
I can appreciate that supporting the flexible approach in `smartslice` might cause a whole lot more work. So it's probably not worth it right now.

2020-11-06 23:30 UTC, jlselden commented on pywim/fea/result.py
> +        self.model_regions = WimList(ModelRegion)
I agree with keeping it simple now with an eye toward the more general approach in the future.

2020-11-07 13:48 UTC, bradymadams approved these changes

2020-11-07 13:48 UTC, merged