Allow the validate button to accept cubic
tetonsim/pywim pull request #78
Opened 2021-01-21 21:17 UTC by jake-kirkland-teton

Closes is-cura-ui #369

2021-01-21 21:18 UTC, jake-kirkland-teton commented
Let me adjust the unit tests real fast.

2021-01-22 14:26 UTC, bradymadams requested changes
Just need to rename the trihexagon type, and then also need to increment the version (in `pywim/_version.py`)

2021-01-22 14:26 UTC, bradymadams commented on pywim/am.py
> +    tri_hexagon = 4
Good idea adding a separate unsupported pattern so the unit tests can remain. Let's rename to `trihexagon` to match [Cura](https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json#L1730), which will make it a little easier to reference between Smart Slice and Cura if we ever need to.

2021-01-22 16:05 UTC, jake-kirkland-teton commented on pywim/am.py
> +    tri_hexagon = 4
Ah gotcha. I should have checked that. I have it changed.

2021-01-22 16:12 UTC, bradymadams approved these changes

2021-01-22 16:13 UTC, merged