R21.0 non manifold detection
tetonsim/pywim pull request #87
Opened 2021-05-17 23:03 UTC by AijunHall

This is expected to work together with my other PR in is-cura-ui

For now this is only a check for non-manifold edges. My goal is that the non manifold exception can be used as a framework for all the other possible checks we can do for undesirable geometry - particularly with the disagreeing normals.

2021-05-17 23:50 UTC, jlselden approved these changes
Good basic structure and logic for beginning the non-manifold checks.

2021-05-18 00:05 UTC, bradymadams requested changes
Looks good. I have a few requests. Mostly centered around giving the calling code more flexibility.

2021-05-18 00:05 UTC, bradymadams commented on pywim/geom/tri.py
> +                    self.non_manifold_warning = True
I think we should add up all of the mesh warnings into a list, so after the mesh analysis we can issue a more detailed description of any problems. So maybe something like this:

```python
# in constructor
self._mesh_warnings = []

# in _compute_edges
if len(tris) != 2:
    self._mesh_warnings.append(NonManifoldEdge(edge))

# new class function
def warnings(self) -> List[MeshException]:
    return self._mesh_warnings
```

Then the calling code can give detailed descriptions, or make more informative decisions, if necessary.

2021-05-18 01:24 UTC, AijunHall commented on pywim/geom/tri.py
> +        self._strict_edge_definition = False
> I think it's entirely possible we might want to ignore dangling edges for surface selection but also not get an exception. That's probably the default setup we'll want to use in the Cura plug-in.

When you say "not get an exception", do you mean an exception that interrupts the mesh analysis? 

We want the dangling edge exceptions to always be added to the mesh warnings right? That way it can be accounted for without being raised and stopping the rest of the analysis. That's what I'm assuming you mean by this is the default setup we want for the plugin

2021-05-18 01:30 UTC, AijunHall commented on pywim/geom/tri.py
> +                    self.non_manifold_warning = True
Since these NonManifold Exceptions are initialized with the specific problem geometry, its ok to have multiple instances of the same Exception in the mesh warnings right?

For example the non-manifold cube STL you sent me a while ago has multiple dangling edges, so this mesh warning list would include every dangling edge

2021-05-18 01:42 UTC, bradymadams commented on pywim/geom/tri.py
> +        self._strict_edge_definition = False
Yep, that's what I mean. Basically, we want to retain the current functionality (ignore dangling edges). And with your added logic we want to not raise exceptions when they are detected (by default for now). So, if I'm understanding things correctly, we'll need two flags to manage that.

2021-05-18 01:44 UTC, bradymadams commented on pywim/geom/tri.py
> +                    self.non_manifold_warning = True
Yep, they will just be separate instances of the same class. Just as if it was a regular class (not derived from Exception).

2021-05-18 17:06 UTC, bradymadams requested changes

2021-05-18 17:06 UTC, bradymadams commented on pywim/geom/tri.py
>                  continue
I'm not sure I understand the new use of `_strict_edge_definition`. Before that was used to `continue` in the loop so that the edge was ignored. I think we want to retain the use of this flag. And we should remove any check on `_strict_edge_definition` for appending to `_mesh_warnings` (line 434). Just always add the warnings to that list - it won't hurt anything.

2021-05-18 17:36 UTC, AijunHall commented on pywim/geom/tri.py
>                  continue
https://github.com/tetonsim/pywim/blob/88c4e4ac97c06f5aea221a1a259ae8598a0f507b/pywim/geom/tri.py#L400-L405

Right now, theres these two separate length checks here. One is used with `_strict_edge_definition` to continue when an edge has more than 2 attached triangles. The other continues when an edge only has 1 attached triangle.

It's my understanding that for proper manifold geometry, all edges need to have exactly 2 attached triangles. So I thought I'd use `_strict_edge_definition` to combine the two different length checks since they both are categorized as "non manifold" whether an edge has 3 or 1 attached triangle.

2021-05-18 18:04 UTC, AijunHall commented on pywim/geom/tri.py
>                  continue
I've put `_strict_edge_definition` back where it was previously, if that's preferable.

2021-05-18 18:05 UTC, bradymadams commented on pywim/geom/tri.py
>                  continue
The main thing I want to ensure is that the surface selection functions do not operate any differently than they did prior. It does seem like that could potentially happen. We probably want to _always_ ignore edges with only one triangle since they can't be used in surface selection (just like we were before). And I think we want to always create the warnings even if `_strict_edge_definition` is False. It gives the calling code the information to do with whatever it wants.

2021-05-18 19:10 UTC, bradymadams approved these changes
Looks good. I'll merge after the related is-cura-ui PR is approved.

2021-05-20 13:02 UTC, merged