R21.1 mod mesh validation
tetonsim/pywim pull request #89
Opened 2021-06-17 21:33 UTC by AijunHall

This PR works with my other PR in is-cura-ui

Changing the existing Infill properties in the necessary print parameters would affect all the existing pywim infill activity/validation, so I just opted to add in the Cura property keys so that they are recognized in the plugin.

I'm a bit nervous that this would affect other aspects within pywim, but with my testing so far it hasn't caused issues.

2021-06-17 22:05 UTC, bradymadams requested changes

2021-06-17 22:05 UTC, bradymadams commented on pywim/chop/mesh.py
> +    def __init__(self, name=None, mesh_type=1):
Use the enumerator, instead of the value. Enumerators are designed specifically to avoid the use of "magic numbers" :slightly_smiling_face: 

```python
def __init__(self, name=None, mesh_type=MeshType.normal):
```

2021-06-17 22:05 UTC, bradymadams commented on pywim/smartslice/val.py
> +    'infill.orientation', # Won't be recognized by Cura
Can you explain what "Won't be recognized by Cura" means?

2021-06-18 00:13 UTC, AijunHall commented on pywim/smartslice/val.py
> +    'infill.orientation', # Won't be recognized by Cura
These 3 infill properties when used in Cura return None, so I wanted to show that explicitly. The comments might be redundant/unecissary since the corresponding cura infill property keys are right below.

`getProperty("infill.pattern")` vs. `getProperty("infill_pattern")`
`getProperty("infill.density")` vs `getProperty("infill_sparse_density")`
`getProperty("infill.orientation")` vs `getProperty("infill_angles")`

2021-06-18 14:54 UTC, bradymadams requested changes

2021-06-18 14:54 UTC, bradymadams commented on pywim/chop/mesh.py
> +        self.type = MeshType(mesh_type)
`self.type = mesh_type` since mesh_type is of type `MeshType` now.

2021-06-24 13:41 UTC, bradymadams approved these changes

2021-06-24 13:41 UTC, merged