R21.1 validation consolidation
tetonsim/pywim pull request #94
Opened 2021-08-11 21:39 UTC by AijunHall

This is meant to replace the plugin-side validation for user entered skin angles and infill angles. I was running into typing issues with the job creation when trying to validate directly from the top level `print_config.skin_orientations` and `print_config.infill.orientation`, so I'm opting to only use the auxiliary dictionary here since that stores the user's input regardless of whether it was a valid entry or not.

This works off my [is-cura-ui PR](https://github.com/tetonsim/is-cura-ui/pull/574)

2021-08-11 21:40 UTC, AijunHall commented
Didn't realize these were failing to build, gotta fix that first.

2021-08-11 21:55 UTC, AijunHall commented
Turning this into a draft as I edit the unittests

2021-08-17 13:53 UTC, bradymadams requested changes
Looks pretty good. Just the one question. And can you add type annotations to all of the new functions you created?

2021-08-17 13:53 UTC, bradymadams commented on pywim/smartslice/val.py
> +                return False
What's wrong with a value starting with `0`? For instance I would consider `'05'` to be a valid string representation of the number 5. Is the list parser unable to handle those numbers?

2021-08-17 13:53 UTC, bradymadams commented on pywim/smartslice/val.py
> +def is_valid_curalist(cura_list):
```python
def is_valid_curalist(cura_list: Any) -> bool:
```

2021-08-18 03:39 UTC, AijunHall commented on pywim/smartslice/val.py
> +                return False
My goal with this is to mimic the UM SettingFunction results when parsing these list values.

When a user enters a list value with a beginning 0 in the plugin, the SettingFunction returns None. So I think even if we evaluated these cases for the user (`05` -> `5`), it wouldn't be practical since Cura has already determined the user input is invalid.

2021-08-23 14:05 UTC, bradymadams requested changes
Still need type annotations for the return types on several functions.

2021-08-24 19:49 UTC, bradymadams approved these changes

2021-08-24 19:49 UTC, merged